version: "3.0"

services:
  fan:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/jikescrapy

    command: ["scrapy", "crawl", "jike_fan", "--logfile=jike_fan.log"]
  user:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/jikescrapy

    command: ["scrapy", "crawl", "jike_user", "--logfile=jike_user.log"]
  redis:
    image: redis:latest
