version: "3.0"

services:
  fan:
    image: scrapy:jike
    depends_on:
      - redis
    volumes:
      - .:/jikescrapy

    command: ["scrapy", "crawl", "jike_fan", "--logfile=jike_fan.log"]
  user:
    image: scrapy:jike
    depends_on:
      - redis
    volumes:
      - .:/jikescrapy

    command: ["scrapy", "crawl", "jike_user", "--logfile=jike_fan.log"]
  redis:
    image: redis:latest
